import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 56,
    backgroundColor: "#F4F6FB",
  },
  // ─── Hero (à vista só sem seleção/busca) ───
  hero: {
    marginBottom: 3,
  },
  title: {
    fontSize: 36,
    fontFamily: "SpaceGrotesk_700Bold",
    color: "#152965",
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 15,
    color: "#666",
    marginTop: 6,
    lineHeight: 22,
  },
  subtitleStatic: {
    fontSize: 15,
    color: "#3970c3",
    lineHeight: 22,
  },
  subtitleWord: {
    fontFamily: "SpaceGrotesk_600SemiBold",
    fontWeight: "600",
    color: "#152965",
    fontSize: 15,
    lineHeight: 22,
  },
  /** Wrapper que reserva altura via espaçador invisível */
  subtitleContainer: {
    marginTop: 6,
    position: "relative",
  },
  /** Espaçador invisível — define a altura do container */
  subtitleSpacer: {
    opacity: 0,
    // pointer-events none em RN não é necessário; texto invisível já é inerte
  },
  /** Camada A ou B posicionada sobre o espaçador */
  subtitleLayer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    fontSize: 15,
    color: "#3970c3",
    lineHeight: 22,
  },
  input: {
    backgroundColor: "#fff",
    padding: 14,
    borderRadius: 12,
    fontSize: 15,
    marginBottom: 14,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  mapContainer: {
    width: "100%",
    height: 200,
    borderRadius: 16,
    marginBottom: 12,
    overflow: "hidden",
  },
  map: {
    flex: 1,
  },
  mapInfoBubble: {
    position: "absolute",
    top: 10,
    alignSelf: "center",
    backgroundColor: "rgba(255,255,255,0.96)",
    borderRadius: 20,
    paddingVertical: 7,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 5,
    maxWidth: "85%",
  },
  mapInfoName: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1A1A1A",
    flexShrink: 1,
  },
  mapInfoDistance: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1A1A1A",
  },
  listArea: {
    flex: 1,
  },
  callout: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 14,
    width: 210,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 8,
  },
  calloutTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1A1A1A",
    marginBottom: 6,
  },
  calloutDecision: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1A1A1A",
    marginBottom: 4,
  },
  calloutWait: {
    fontSize: 12,
    color: "#555",
  },
  calloutDistance: {
    fontSize: 12,
    color: "#1A1A1A",
    fontWeight: "600",
    marginBottom: 6,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: "#888",
    marginBottom: 10,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  // Botão Voltar (substitui sectionTitle quando há seleção ou busca)
  voltarBtn: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    paddingVertical: 4,
  },
  voltarBtnText: {
    fontSize: 14,
    color: "#1A1A1A",
    fontWeight: "600",
  },
  marketRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 14,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  marketRowActive: {
    borderWidth: 1.5,
    borderColor: "#3970c3",
  },
  dotWrapper: {
    width: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  dotRing: {
    position: "absolute",
    width: 14,
    height: 14,
    borderRadius: 7,
  },
  dotCore: {
    width: 10,
    height: 10,
    borderRadius: 5,
    // shadowColor é aplicado inline (dinâmico por cor do fluxo)
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 7,
    shadowOpacity: 0.75,
    elevation: 3,
  },
  marketRowText: {
    flex: 1,
  },
  marketRowName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1A1A1A",
    marginBottom: 2,
  },
  marketRowDecision: {
    fontSize: 13,
    color: "#666",
  },
  emptyText: {
    fontSize: 14,
    color: "#999",
    textAlign: "center",
    marginTop: 20,
  },
  report: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 18,
    marginTop: 0,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  reportName: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1A1A1A",
    marginBottom: 14,
  },

  reportRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 14,
  },
  reportChip: {
    flex: 1,
    backgroundColor: "#EEF3FB",
    borderRadius: 12,
    padding: 12,
  },
  chipLabel: {
    fontSize: 11,
    color: "#888",
    fontWeight: "600",
    textTransform: "uppercase",
    marginBottom: 4,
  },
  chipValue: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
    textTransform: "capitalize",
  },
  divider: {
    height: 1,
    backgroundColor: "#e0e0e2",
    marginBottom: 14,
  },
  reportDecision: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1A1A1A",
    marginBottom: 6,
  },
  reportWait: {
    fontSize: 14,
    color: "#555",
  },
  snapshotTime: {
    fontSize: 11,
    color: "#AAAAAA",
    marginTop: 10,
    textAlign: "right",
  },
  navigateBtn: {
    marginTop: 16,
    backgroundColor: "#152965",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
  },
  navigateBtnText: {
    color: "#fff",
    fontSize: 15,
    fontFamily: "SpaceGrotesk_600SemiBold",
    letterSpacing: 0.3,
  },
  // ─── Relato inline (antes do Ir agora) ───
  inlineReportSection: {
    marginTop: 16,
    marginBottom: 4,
    padding: 14,
    backgroundColor: "#F4F6FB",
    borderRadius: 12,
  },
  inlineReportLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#888",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 10,
  },
  inlineReportBtns: {
    flexDirection: "row",
    gap: 8,
  },
  inlineReportBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    paddingVertical: 9,
    borderRadius: 10,
    borderWidth: 1.5,
    backgroundColor: "#fff",
  },
  inlineReportBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#1A1A1A",
  },
  inlineReportConfirm: {
    fontSize: 13,
    fontWeight: "600",
    textAlign: "center",
  },
  feedbackDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  // Resultados de busca (acima do mapa)
  searchResults: {
    maxHeight: 200,
    marginBottom: 10,
    backgroundColor: "#fff",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  searchResultRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#F0F0F0",
  },
  searchResultRowActive: {
    backgroundColor: "#F0F7F0",
  },
  searchResultName: {
    fontSize: 14,
    fontWeight: "600",
    color: "#1A1A1A",
    marginLeft: 10,
    flex: 1,
  },
  // Botão voltar herdado (mantido por compat) — use voltarBtn no fluxo principal
  backBtn: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F0F0F0",
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 14,
    marginBottom: 14,
  },
  backBtnText: {
    fontSize: 13,
    color: "#555",
    fontWeight: "600",
  },
});

